// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션·CLI는 다이렉트 연결(5432)을 써야 한다. 런타임 풀드 연결은 lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
